import type { CapacitorConfig } from '@capacitor/cli'

const config: CapacitorConfig = {
  // Must match the applicationId in android/app/build.gradle
  appId: 'studio.socialmate.app',
  appName: 'SocialMate',

  // Point the WebView at the live production URL.
  // This means no static export is needed — the app is just a WebView wrapper.
  server: {
    url: 'https://socialmate.studio',
    cleartext: false,       // HTTPS only
    androidScheme: 'https', // required for cookies / Supabase auth to work on Android
  },

  android: {
    // These paths are relative to the android/ directory generated by `npx cap add android`
    buildOptions: {
      keystorePath:    process.env.KEYSTORE_PATH    || undefined,
      keystoreAlias:   process.env.KEYSTORE_ALIAS   || undefined,
      keystorePassword:process.env.KEYSTORE_PASSWORD|| undefined,
    },
  },

  plugins: {
    // Push notifications — maps to our existing VAPID web push
    PushNotifications: {
      presentationOptions: ['badge', 'sound', 'alert'],
    },
    // Allow the WebView to open external URLs in the system browser
    Browser: {},
    // Status bar styling
    StatusBar: {
      style: 'Dark',
      backgroundColor: '#000000',
    },
    SplashScreen: {
      launchShowDuration: 1500,
      backgroundColor: '#000000',
      androidSplashResourceName: 'splash',
      showSpinner: false,
    },
  },
}

export default config
