export const dynamic = 'force-dynamic'
import { serve } from 'inngest/next'
import {
  inngest,
  publishScheduledPost,
  weeklyDigest,
  fetchPostAnalytics,
  evergreenRecycler,
  discordWelcomePoller,
  sendNotification,
  creditLowChecker,
  onboardingSequence,
  competitorPostFetcher,
  competitorAlerts,
  enkiPaperTradingScan,
  enkiCloudRunnerScan,
  enkiTruthModeScan,
  enkiWeeklySummary,
  studioStaxRenewalEmails,
  resetSomaCredits,
  streakNotifications,
  somaAutopilotRun,
  postPerformanceAlerts,
  publishScheduledTiktokPosts,
} from '@/lib/inngest'
import { newsletterAgent, clientReportAgent, repurposeAgent, captionAgent, trendScoutAgent, inboxAgent } from '@/lib/inngest-agents'
import { hermesFollowUpCron } from '@/lib/inngest-hermes'

export const { GET, POST, PUT } = serve({
  client: inngest,
  functions: [
    publishScheduledPost,
    weeklyDigest,
    fetchPostAnalytics,
    evergreenRecycler,
    discordWelcomePoller,
    sendNotification,
    creditLowChecker,
    onboardingSequence,
    competitorPostFetcher,
    competitorAlerts,
    enkiPaperTradingScan,
    enkiCloudRunnerScan,
    enkiTruthModeScan,
    enkiWeeklySummary,
    studioStaxRenewalEmails,
    resetSomaCredits,
    streakNotifications,
    somaAutopilotRun,
    postPerformanceAlerts,
    newsletterAgent,
    clientReportAgent,
    repurposeAgent,
    captionAgent,
    trendScoutAgent,
    inboxAgent,
    publishScheduledTiktokPosts,
    hermesFollowUpCron,
  ],
})
