import type { Metadata } from 'next'
import Link from 'next/link'
import PublicLayout from '@/components/PublicLayout'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
import BlogClientList from '@/components/BlogClientList'

export const metadata: Metadata = {
  title: 'Blog — SocialMate',
  description: 'Guides, tips, and insights on social media scheduling, content strategy, AI tools, and growing your audience across Bluesky, Discord, Mastodon, and more.',
  openGraph: {
    type:        'website',
    title:       'SocialMate Blog — Social Media Guides & Tips',
    description: 'Guides, tips, and insights on social media scheduling, content strategy, AI tools, and growing your audience across Bluesky, Discord, Mastodon, and more.',
    url:         'https://socialmate.studio/blog',
    images: [{ url: 'https://socialmate.studio/og-image.png', width: 1270, height: 760, alt: 'SocialMate Blog' }],
  },
  twitter: {
    card:        'summary_large_image',
    title:       'SocialMate Blog — Social Media Guides & Tips',
    description: 'Guides, tips, and insights on social media scheduling, AI tools, and growing your audience.',
    images:      ['https://socialmate.studio/og-image.png'],
  },
  alternates: { canonical: 'https://socialmate.studio/blog' },
}

async function getDbPosts() {
  try {
    const admin = getSupabaseAdmin()
    const { data } = await admin
      .from('blog_posts')
      .select('slug, title, excerpt, category, author, published_at, content')
      .order('published_at', { ascending: false })
      .limit(30)
    if (!data) return []
    return data.map((d: any) => {
      const wordCount = (d.content || '').trim().split(/\s+/).length
      const readMins  = Math.max(1, Math.round(wordCount / 200))
      return {
        slug:      d.slug as string,
        title:     d.title as string,
        date:      new Date(d.published_at).toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
        category:  (d.category || 'Studio Stax') as string,
        excerpt:   (d.excerpt || '') as string,
        readTime:  `${readMins} min read`,
        emoji:     '🛠️',
        featured:  false,
      }
    })
  } catch {
    return []
  }
}

const STATIC_POSTS = [
  { slug: 'why-we-built-socialmate',                         title: 'Why We Built SocialMate: The Full Story',                        date: 'March 2026',    category: 'Our Story',   excerpt: 'Built by a deli worker in spare moments. Here\'s why SocialMate exists and what we\'re building toward.',              readTime: '4 min read', emoji: '❤️',  featured: true  },
  { slug: 'socialmate-gives-back-sm-give',                   title: 'How SocialMate Gives Back: Introducing SM-Give',                 date: 'April 2026',    category: 'Our Story',   excerpt: 'Every subscription, every donation, every unclaimed affiliate check — a piece goes to real people who need it most.',   readTime: '3 min read', emoji: '🫶',  featured: false },
  { slug: 'discord-scheduling-grow-your-server',             title: 'How to Schedule Discord Posts and Grow Your Server in 2026',    date: 'April 2026',    category: 'Guides',      excerpt: 'Discord isn\'t just for gaming anymore. Here\'s how to use scheduled posts to keep your community engaged daily.',   readTime: '5 min read', emoji: '💬',  featured: false },
  { slug: 'mastodon-scheduling-free-tool',                   title: 'How to Schedule Mastodon Posts for Free (No Paid Tools)',        date: 'April 2026',    category: 'Guides',      excerpt: 'Mastodon has no algorithm — which means consistency is everything. Here\'s a free way to stay consistent.',            readTime: '4 min read', emoji: '🐘',  featured: false },
  { slug: 'how-to-repurpose-content-across-platforms',       title: 'How to Repurpose Content Across 4 Platforms Without Burning Out', date: 'April 2026',   category: 'Tips',        excerpt: 'You don\'t need four different content strategies. One post, four platforms, zero burnout — here\'s the system.',        readTime: '5 min read', emoji: '♻️', featured: false },
  { slug: 'how-to-schedule-posts-on-bluesky',                title: 'How to Schedule Posts on Bluesky in 2026',                       date: 'March 2026',    category: 'Guides',      excerpt: 'Bluesky is growing fast. Here\'s how to schedule posts, maintain consistency, and grow your following.',                readTime: '4 min read', emoji: '🦋',  featured: false },
  { slug: 'social-media-scheduling-for-small-business',      title: 'Social Media Scheduling for Small Businesses: The Practical Guide', date: 'March 2026', category: 'Guides',      excerpt: 'Small businesses don\'t need a $99/month tool to post consistently. Here\'s a practical system that works.',           readTime: '5 min read', emoji: '🏪',  featured: false },
  { slug: 'free-social-media-tools-for-creators',            title: 'The Best Free Social Media Tools for Creators in 2026',          date: 'March 2026',    category: 'Resources',   excerpt: 'A complete list of free tools for creators — scheduling, analytics, design, and AI — with honest takes.',              readTime: '6 min read', emoji: '🎨',  featured: false },
  { slug: 'how-to-grow-bluesky-following',                   title: 'How to Grow Your Bluesky Following in 2026',                     date: 'March 2026',    category: 'Growth',      excerpt: 'Bluesky rewards genuine interaction over gaming the algorithm. Here\'s what\'s actually working.',                      readTime: '5 min read', emoji: '📈',  featured: false },
  { slug: 'social-media-scheduling-vs-posting-manually',     title: 'Scheduling vs. Posting Manually: Which Is Better?',              date: 'March 2026',    category: 'Tips',        excerpt: 'The debate has been settled by data. Here\'s when to schedule, when to post live, and how to combine both.',           readTime: '4 min read', emoji: '⏱️', featured: false },
  { slug: 'best-free-social-media-scheduler-2025',           title: 'The Best Free Social Media Scheduler in 2026 (No Credit Card)',  date: 'Feb 2026',      category: 'Guides',      excerpt: 'Most "free" schedulers are just trials. SocialMate is genuinely free — here\'s exactly what you get.',                 readTime: '5 min read', emoji: '📅',  featured: false },
  { slug: 'how-to-use-ai-for-social-media-captions',         title: 'How to Use AI to Write Better Social Media Captions',            date: 'Feb 2026',      category: 'Tips',        excerpt: 'AI caption tools can save hours every week. Here\'s how to use them without sounding like a robot.',                    readTime: '3 min read', emoji: '✍️', featured: false },
  { slug: 'why-your-hashtag-strategy-isnt-working',          title: 'Why Your Hashtag Strategy Isn\'t Working (And How to Fix It)',   date: 'Jan 2026',      category: 'Tips',        excerpt: 'Spamming 30 hashtags stopped working years ago. Here\'s what actually drives reach in 2026.',                          readTime: '4 min read', emoji: '#️⃣', featured: false },
  { slug: 'real-cost-of-social-media-management-tools-2025', title: 'The Real Cost of Social Media Management Tools in 2026',        date: 'Dec 2025',      category: 'Guides',      excerpt: 'We did the math on what popular scheduling tools actually cost. The numbers are eye-opening.',                          readTime: '5 min read', emoji: '💰',  featured: false },
  { slug: 'how-to-schedule-telegram-posts-free',             title: 'How to Schedule Telegram Posts for Free in 2026',               date: 'April 2026',    category: 'Guides',      excerpt: 'Telegram is one of the most underrated platforms for creators and communities. Here\'s how to schedule posts to it without paying for anything.',   readTime: '5 min read', emoji: '✈️',  featured: false },
  { slug: 'bluesky-vs-twitter-where-to-post-2026',           title: 'Bluesky vs Twitter/X in 2026: Where Should You Actually Post?', date: 'April 2026',    category: 'Comparisons', excerpt: 'Bluesky has crossed 30 million users. X/Twitter still has hundreds of millions. Here\'s the honest breakdown of where your time is better spent.',  readTime: '5 min read', emoji: '⚖️',  featured: false },
  { slug: 'social-media-content-calendar-template-2026',     title: 'How to Build a Social Media Content Calendar (Free Template + System)', date: 'April 2026', category: 'Resources', excerpt: 'A content calendar you actually use is worth more than a perfect one you abandon. Here\'s a simple system and a free template.',                  readTime: '6 min read', emoji: '📅',  featured: false },
  { slug: 'best-time-to-post-on-bluesky',                    title: 'The Best Times to Post on Bluesky in 2026 (Data + Tips)',       date: 'April 2026',    category: 'Tips',        excerpt: 'Bluesky is mostly chronological, which means timing matters more here than on algorithm-heavy platforms. Here\'s what\'s working.',                readTime: '4 min read', emoji: '💡',  featured: false },
  { slug: 'discord-community-management-guide',              title: 'Discord Community Management: How to Keep Members Engaged in 2026', date: 'April 2026', category: 'Guides',      excerpt: 'Most Discord servers go quiet within 60 days of launch. Here\'s what separates the ones that stay active from the ones that become ghost towns.',  readTime: '6 min read', emoji: '💬',  featured: false },
  { slug: 'social-media-automation-solo-creators',           title: 'Social Media Automation for Solo Creators: Do More in Less Time', date: 'April 2026',   category: 'Tips',        excerpt: 'Solo creators who automate the right things post more consistently, burn out less, and grow faster. Here\'s exactly what to automate.',           readTime: '5 min read', emoji: '💡',  featured: false },
  { slug: 'free-hootsuite-alternative-2026',                 title: 'The Best Free Hootsuite Alternative in 2026',                    date: 'April 2026',    category: 'Comparisons', excerpt: 'Hootsuite removed their free plan. Prices start at $99/month. Here are the best free alternatives that actually work.',                           readTime: '5 min read', emoji: '⚖️',  featured: false },
  { slug: 'how-to-grow-discord-server-2026',                 title: 'How to Grow a Discord Server from 0 in 2026',                   date: 'April 2026',    category: 'Growth',      excerpt: 'Growing a Discord server from scratch is slow if you don\'t have a system. Here\'s a proven approach for getting your first 500 members.',        readTime: '6 min read', emoji: '📈',  featured: false },
  { slug: 'ai-social-media-tools-free-2026',                 title: 'The Best Free AI Social Media Tools in 2026',                   date: 'April 2026',    category: 'Resources',   excerpt: 'AI tools for social media have gotten genuinely useful in 2026. Here\'s a guide to the best free options and what they\'re actually good at.',     readTime: '5 min read', emoji: '🧰',  featured: false },
  { slug: 'how-to-post-consistently-social-media',           title: 'How to Post Consistently on Social Media (Without Burning Out)', date: 'April 2026',    category: 'Tips',        excerpt: 'Consistency is the single biggest factor in social media growth. Here\'s a system for staying consistent that doesn\'t require willpower.',        readTime: '5 min read', emoji: '💡',  featured: false },
  { slug: 'mastodon-vs-bluesky-2026',                        title: 'Mastodon vs Bluesky in 2026: Which Decentralized Platform Should You Use?', date: 'April 2026', category: 'Comparisons', excerpt: 'Both are open, decentralized alternatives to X/Twitter. They\'re quite different. Here\'s how to decide which one is worth your time.',      readTime: '5 min read', emoji: '⚖️',  featured: false },
  { slug: 'social-media-scheduling-agencies-freelancers',    title: 'Social Media Scheduling for Agencies and Freelancers: The Practical Guide', date: 'April 2026', category: 'Guides', excerpt: 'Managing social media for multiple clients is a different challenge. Here\'s how to build a system that scales without burning out.',             readTime: '6 min read', emoji: '📋',  featured: false },
  // 14 new posts (Apr 2026)
  { slug: 'best-social-media-scheduler-creators-2026',       title: 'The Best Social Media Scheduler for Creators in 2026 (Free Options Compared)', date: 'April 2026', category: 'Comparisons', excerpt: 'Most free schedulers are trials in disguise. Here\'s an honest comparison of the best options for creators in 2026.',                              readTime: '6 min read', emoji: '⚖️',  featured: false },
  { slug: 'how-to-schedule-posts-instagram-free',            title: 'How to Schedule Instagram Posts for Free in 2026',                             date: 'April 2026', category: 'Guides',      excerpt: 'Instagram scheduling without paying $50/month is possible. Here\'s how to do it and what tools actually work for free.',                          readTime: '5 min read', emoji: '📷',  featured: false },
  { slug: 'social-media-content-ideas-2026',                 title: '50 Social Media Content Ideas That Work in 2026',                              date: 'April 2026', category: 'Tips',        excerpt: 'Staring at a blank content calendar? Here are 50 proven ideas across every platform — pick what fits your brand.',                               readTime: '7 min read', emoji: '💡',  featured: false },
  { slug: 'how-to-use-bluesky-for-business',                 title: 'How to Use Bluesky for Business (Complete Guide 2026)',                        date: 'April 2026', category: 'Guides',      excerpt: 'Bluesky has crossed 30 million users and is growing fast. Here\'s how businesses are actually using it.',                                         readTime: '6 min read', emoji: '🦋',  featured: false },
  { slug: 'pinterest-scheduling-free-tools',                 title: 'Best Free Pinterest Scheduling Tools in 2026',                                 date: 'April 2026', category: 'Comparisons', excerpt: 'Pinterest rewards consistent posting. Here\'s which free tools actually work for scheduling Pins without a monthly fee.',                         readTime: '5 min read', emoji: '📌',  featured: false },
  { slug: 'social-media-burnout-creators',                   title: 'Social Media Burnout Is Real — Here\'s How to Post Without Burning Out',       date: 'April 2026', category: 'Tips',        excerpt: 'Posting every day is not sustainable for most people. Here\'s a system for staying consistent without the mental cost.',                          readTime: '5 min read', emoji: '🔥',  featured: false },
  { slug: 'how-to-grow-mastodon-following',                  title: 'How to Grow Your Mastodon Following in 2026',                                  date: 'April 2026', category: 'Growth',      excerpt: 'Mastodon has no algorithm and no ad-driven discovery. Growth works differently here — and that\'s actually a good thing.',                        readTime: '5 min read', emoji: '🐘',  featured: false },
  { slug: 'small-business-social-media-guide-2026',          title: 'The Complete Social Media Guide for Small Businesses in 2026',                 date: 'April 2026', category: 'Guides',      excerpt: 'Running social media for a small business is different from being an influencer. Here\'s a practical guide for the real world.',                  readTime: '7 min read', emoji: '🏪',  featured: false },
  { slug: 'free-link-in-bio-tools',                          title: 'Best Free Link-in-Bio Tools in 2026 (Linktree Alternatives)',                  date: 'April 2026', category: 'Comparisons', excerpt: 'Linktree is the default — but it\'s not the best option for everyone. Here are the top free alternatives in 2026.',                             readTime: '5 min read', emoji: '🔗',  featured: false },
  { slug: 'twitter-x-alternatives-2026',                     title: 'The Best Twitter/X Alternatives in 2026 (And Where Creators Are Going)',       date: 'April 2026', category: 'Growth',      excerpt: 'Creators are spreading out. Bluesky, Mastodon, Threads — here\'s where people are going and what\'s actually growing.',                          readTime: '5 min read', emoji: '📊',  featured: false },
  { slug: 'content-calendar-for-small-business',             title: 'How to Build a Content Calendar for Your Small Business (Free Template)',      date: 'April 2026', category: 'Resources',   excerpt: 'A content calendar prevents the "what do I post today?" panic. Here\'s how to build one that actually gets used.',                                readTime: '6 min read', emoji: '📅',  featured: false },
  { slug: 'social-media-analytics-free-tools',               title: 'Best Free Social Media Analytics Tools in 2026',                               date: 'April 2026', category: 'Comparisons', excerpt: 'Most analytics tools cost $50-$250/month. Here are the ones that give you real data for free in 2026.',                                           readTime: '5 min read', emoji: '📈',  featured: false },
  { slug: 'discord-for-creators-2026',                       title: 'Why Every Creator Should Have a Discord Server in 2026',                       date: 'April 2026', category: 'Growth',      excerpt: 'Discord is the most underrated creator tool right now. Here\'s why every creator should be building a server.',                                   readTime: '5 min read', emoji: '💬',  featured: false },
  { slug: 'how-to-repurpose-one-post-ten-platforms',         title: 'How to Turn One Post Into Content for 10 Platforms',                           date: 'April 2026', category: 'Tips',        excerpt: 'Creating ten separate posts is not sustainable. Here\'s the system for turning one core idea into content across 10 platforms.',                 readTime: '6 min read', emoji: '♻️',  featured: false },
  // 20 new posts (Apr 2026 batch 3)
  { slug: 'x-twitter-scheduling-free',                    title: 'How to Schedule X (Twitter) Posts for Free in 2026',                    date: 'April 2026', category: 'Guides',      excerpt: 'X removed their free scheduling tools. Here\'s how to schedule tweets for free in 2026 without paying $100/month for the API tier.', readTime: '5 min read', emoji: '🐦', featured: false },
  { slug: 'bluesky-for-creators-2026',                    title: 'Bluesky for Creators: The Complete 2026 Guide',                          date: 'April 2026', category: 'Guides',      excerpt: 'Bluesky crossed 30M users and keeps growing. Here\'s everything creators need to know about building an audience on Bluesky.', readTime: '6 min read', emoji: '🦋', featured: false },
  { slug: 'social-media-tools-comparison-2026',           title: 'The Complete Social Media Tools Comparison for 2026',                    date: 'April 2026', category: 'Comparisons', excerpt: 'Buffer, Hootsuite, Later, SocialPilot — we compare every major tool on pricing, features, and free plan quality.', readTime: '8 min read', emoji: '⚖️', featured: false },
  { slug: 'discord-bot-vs-scheduler',                     title: 'Discord Bot vs Social Media Scheduler: Which Should You Use?',           date: 'April 2026', category: 'Guides',      excerpt: 'Discord bots and social schedulers solve different problems. Here\'s when to use each — and when you need both.', readTime: '5 min read', emoji: '🤖', featured: false },
  { slug: 'mastodon-guide-2026',                          title: 'The Complete Mastodon Guide for 2026',                                   date: 'April 2026', category: 'Guides',      excerpt: 'Mastodon is different from every other social network. No algorithm, no ads, federated servers. Here\'s how it actually works.', readTime: '7 min read', emoji: '🐘', featured: false },
  { slug: 'free-social-media-scheduler-no-credit-card',  title: 'Free Social Media Schedulers That Don\'t Require a Credit Card',        date: 'April 2026', category: 'Comparisons', excerpt: 'Most "free" tools ask for a card and start billing after 14 days. These ones are actually free — no card required.', readTime: '5 min read', emoji: '💳', featured: false },
  { slug: 'social-media-workflow-creators',               title: 'The Exact Social Media Workflow I Use to Post Consistently',            date: 'April 2026', category: 'Tips',        excerpt: 'Posting consistently doesn\'t require hours of work. Here\'s the exact system that keeps me posting without burning out.', readTime: '6 min read', emoji: '⚙️', featured: false },
  { slug: 'bluesky-algorithm-2026',                       title: 'Does Bluesky Have an Algorithm? What Creators Need to Know',            date: 'April 2026', category: 'Growth',      excerpt: 'Bluesky\'s feed system is very different from Twitter\'s. Understanding it changes how you should post.', readTime: '5 min read', emoji: '📊', featured: false },
  { slug: 'telegram-channel-growth',                      title: 'How to Grow a Telegram Channel from 0 in 2026',                        date: 'April 2026', category: 'Growth',      excerpt: 'Telegram channels can grow fast if you understand the discovery mechanics. Here\'s a practical system for getting your first 1,000 subscribers.', readTime: '6 min read', emoji: '📱', featured: false },
  { slug: 'social-media-scheduling-cost-breakdown',       title: 'The Real Cost of Social Media Scheduling Tools in 2026',                date: 'April 2026', category: 'Comparisons', excerpt: 'We priced out every major social media scheduler for a typical creator workflow. The range is $0 to $300/month — here\'s what you actually need.', readTime: '6 min read', emoji: '💰', featured: false },
  { slug: 'hashtag-strategy-bluesky-mastodon',            title: 'Hashtag Strategy for Bluesky and Mastodon in 2026',                    date: 'April 2026', category: 'Tips',        excerpt: 'Hashtags work differently on Bluesky and Mastodon than on Instagram or Twitter. Here\'s what actually works.', readTime: '5 min read', emoji: '#️⃣', featured: false },
  { slug: 'content-repurposing-system',                   title: 'The Content Repurposing System That Saves 10 Hours a Week',            date: 'April 2026', category: 'Tips',        excerpt: 'Creating unique content for 5 platforms is unsustainable. This repurposing system lets you do more with less.', readTime: '6 min read', emoji: '♻️', featured: false },
  { slug: 'social-media-for-nonprofits',                  title: 'Social Media Scheduling for Nonprofits: Free Tools That Work',         date: 'April 2026', category: 'Guides',      excerpt: 'Nonprofits need social media tools but rarely have the budget. Here are the best free options that don\'t compromise on features.', readTime: '5 min read', emoji: '💙', featured: false },
  { slug: 'best-time-post-discord',                       title: 'Best Time to Post in Discord for Maximum Engagement',                  date: 'April 2026', category: 'Tips',        excerpt: 'Discord engagement is all about timing. Here\'s when to post based on server size, audience timezone, and content type.', readTime: '5 min read', emoji: '⏰', featured: false },
  { slug: 'ai-content-creation-social-media',             title: 'How to Use AI for Social Media Content Creation (Without Sounding Like a Bot)', date: 'April 2026', category: 'Tips', excerpt: 'AI tools can speed up content creation 10x — but most AI-generated posts are obvious and get ignored. Here\'s how to use AI well.', readTime: '5 min read', emoji: '🤖', featured: false },
  { slug: 'social-media-strategy-small-team',             title: 'Social Media Strategy for Small Teams (2-5 People)',                   date: 'April 2026', category: 'Guides',      excerpt: 'Running social media with a small team is a coordination problem as much as a content problem. Here\'s a system that works.', readTime: '6 min read', emoji: '👥', featured: false },
  { slug: 'scheduling-vs-posting-manually-2026',          title: 'Scheduling vs Posting Manually: Which Is Better in 2026?',             date: 'April 2026', category: 'Tips',        excerpt: 'The scheduling vs manual posting debate has a nuanced answer. Here\'s when each approach works and when it doesn\'t.', readTime: '5 min read', emoji: '📅', featured: false },
  { slug: 'grow-audience-multiple-platforms',             title: 'How to Grow an Audience Across Multiple Platforms Simultaneously',     date: 'April 2026', category: 'Growth',      excerpt: 'Building an audience on one platform is hard. Building on five is harder — unless you have a system. Here\'s the one that works.', readTime: '7 min read', emoji: '📈', featured: false },
  { slug: 'social-media-analytics-what-matters',         title: 'Social Media Analytics: What Actually Matters vs What\'s Vanity',     date: 'April 2026', category: 'Analytics',   excerpt: 'Impressions and follower counts feel good but don\'t grow your business. Here\'s which metrics actually matter.', readTime: '5 min read', emoji: '📊', featured: false },
  { slug: 'decentralized-social-media-2026',              title: 'Decentralized Social Media in 2026: Bluesky, Mastodon, and What\'s Next', date: 'April 2026', category: 'Industry', excerpt: 'Decentralized platforms crossed 50M combined users in 2026. Here\'s what\'s happening, why it matters, and where it\'s going.', readTime: '6 min read', emoji: '🌐', featured: false },
  // 27 new posts (Apr 27 2026 — feature & SEO batch)
  { slug: 'what-is-soma-ai-social-media-agent',            title: 'What Is SOMA? The AI Agent That Writes and Schedules Your Posts',                date: 'April 2026', category: 'Features',    excerpt: 'SOMA is not just a scheduler — it\'s an AI agent that reads your content, learns your voice, and generates posts across every platform automatically.', readTime: '5 min read', emoji: '⚡', featured: false },
  { slug: 'how-to-use-soma-social-media-automation',       title: 'How to Use SOMA to Automate Your Social Media (Step-by-Step)',                   date: 'April 2026', category: 'Guides',      excerpt: 'From voice profile to your first auto-generated post in under 10 minutes. A complete walkthrough of SOMA — SocialMate\'s AI media agent.', readTime: '6 min read', emoji: '⚡', featured: false },
  { slug: 'soma-vs-buffer-hootsuite-ai-scheduling',        title: 'SOMA vs Buffer vs Hootsuite: Why AI-Driven Scheduling Is Different',             date: 'April 2026', category: 'Comparisons', excerpt: 'Traditional schedulers require you to write every post manually. SOMA generates them. Here\'s what that difference actually means for your workflow.', readTime: '5 min read', emoji: '⚖️', featured: false },
  { slug: 'ai-marketing-agents-social-media-2026',         title: 'How AI Marketing Agents Are Changing Social Media in 2026',                     date: 'April 2026', category: 'Industry',    excerpt: 'AI agents are moving from "write this caption" to "run this channel." Here\'s what the shift means for creators, marketers, and agencies.', readTime: '6 min read', emoji: '🤖', featured: false },
  { slug: 'soma-safe-autopilot-full-send-explained',       title: 'Safe Mode vs Autopilot vs Full Send: Choosing Your Level of Automation',        date: 'April 2026', category: 'Tips',        excerpt: 'SOMA has three automation levels. Here\'s when each one makes sense — and why starting on Safe Mode is almost always the right move.', readTime: '4 min read', emoji: '💡', featured: false },
  { slug: 'what-is-enki-ai-trading-bot',                   title: 'What Is Enki? The AI Trading Bot Built for Independent Traders',                 date: 'April 2026', category: 'Features',    excerpt: 'Enki is an AI-powered paper and live trading bot with real quant signals — RSI, MACD, ADX, Kelly sizing. Here\'s what it actually does.', readTime: '5 min read', emoji: '📈', featured: false },
  { slug: 'paper-trading-2026-practice-without-losing',    title: 'Paper Trading in 2026: How to Practice Without Losing Real Money',              date: 'April 2026', category: 'Guides',      excerpt: 'Paper trading lets you test strategies with fake money and real data. Here\'s how it works and why it matters before you go live.', readTime: '5 min read', emoji: '📊', featured: false },
  { slug: 'enki-truth-mode-trading-signal-validation',     title: 'Enki Truth Mode: How We Validate Trading Signals Before Going Live',            date: 'April 2026', category: 'Features',    excerpt: 'Truth Mode is a controlled experiment: 50 paper trades per strategy, equity curve vs SPY, no bias. Here\'s how it works and why it matters.', readTime: '5 min read', emoji: '🔍', featured: false },
  { slug: 'social-media-approval-workflow-teams',           title: 'How to Build a Social Media Approval Workflow for Your Team',                   date: 'April 2026', category: 'Teams',       excerpt: 'When multiple people post for a brand, approval workflows prevent mistakes. Here\'s how to set up a system that doesn\'t slow everyone down.', readTime: '5 min read', emoji: '✅', featured: false },
  { slug: 'link-shortener-social-media-why-it-matters',    title: 'Why Link Shorteners Matter for Social Media (And Which to Use)',                date: 'April 2026', category: 'Tips',        excerpt: 'Short links do more than save characters — they track clicks, look cleaner, and work better across platforms. Here\'s what to know in 2026.', readTime: '4 min read', emoji: '🔗', featured: false },
  { slug: 'posting-streak-social-media-consistency',       title: 'How a Posting Streak Keeps You Consistent on Social Media',                     date: 'April 2026', category: 'Growth',      excerpt: 'Streaks work. Not because of gamification tricks, but because they create a daily commitment point. Here\'s how to use one to stay consistent.', readTime: '4 min read', emoji: '🔥', featured: false },
  { slug: 'content-dna-engagement-fingerprint-analytics',  title: 'Content DNA: Understanding Your Social Media Engagement Fingerprint',           date: 'April 2026', category: 'Analytics',   excerpt: 'Every account has a content DNA — the patterns of what works. Here\'s how to find yours and use it to make better decisions faster.', readTime: '5 min read', emoji: '🧬', featured: false },
  { slug: 'unified-social-inbox-manage-replies',           title: 'How to Manage Social Media Replies Without Missing a Single One',               date: 'April 2026', category: 'Guides',      excerpt: 'Switching between Bluesky, Mastodon, Discord, and Telegram to reply to messages is a time drain. A unified inbox solves it. Here\'s how.', readTime: '4 min read', emoji: '📬', featured: false },
  { slug: 'how-to-write-twitter-threads-that-get-read',    title: 'How to Write Twitter/X Threads That Actually Get Read',                        date: 'April 2026', category: 'Tips',        excerpt: 'Most threads lose readers by post 2. Here\'s the structure, opening hooks, and posting format that keeps people reading to the end.', readTime: '5 min read', emoji: '🧵', featured: false },
  { slug: 'brand-voice-ai-social-media-posts',             title: 'Brand Voice AI: How to Make Every AI-Generated Post Sound Like You',           date: 'April 2026', category: 'AI',          excerpt: 'Generic AI posts get ignored. The fix is a defined brand voice that every tool uses as context. Here\'s how to set one up in SocialMate.', readTime: '5 min read', emoji: '🎙️', featured: false },
  { slug: 'content-repurposing-ai-2026',                   title: 'How to Repurpose Content With AI in 2026 (6 Formats From 1 Post)',             date: 'April 2026', category: 'AI',          excerpt: 'One post can become a thread, a newsletter, a caption, a hook, a LinkedIn post, and a long-form article. AI makes that happen in seconds.', readTime: '5 min read', emoji: '♻️', featured: false },
  { slug: 'smart-queue-auto-scheduling-best-times',        title: 'Smart Queue: How to Auto-Schedule Posts at the Best Times for Each Platform',  date: 'April 2026', category: 'Guides',      excerpt: 'Platform-optimal timing is different for Bluesky, Discord, Telegram, and X. Smart Queue handles that automatically. Here\'s how it works.', readTime: '4 min read', emoji: '⚡', featured: false },
  { slug: 'post-as-image-social-media-graphics',           title: 'Post as Image: Why Turning Text Into Graphics Gets More Engagement',           date: 'April 2026', category: 'Tips',        excerpt: 'Text posts are easy to scroll past. Image posts stop the thumb. Here\'s how converting your text to a branded graphic changes your engagement.', readTime: '4 min read', emoji: '📸', featured: false },
  { slug: 'recurring-posts-social-media-automation',       title: 'Recurring Posts: Set It Once and Never Miss a Schedule Again',                 date: 'April 2026', category: 'Features',    excerpt: 'Some content deserves to be shared more than once. Recurring posts let you schedule daily, weekly, bi-weekly, or monthly — automatically.', readTime: '4 min read', emoji: '🔁', featured: false },
  { slug: 'ab-testing-social-media-posts',                 title: 'A/B Testing Your Social Media Posts: How to Know What Actually Works',        date: 'April 2026', category: 'Analytics',   excerpt: 'Most creators guess what works. A/B testing replaces the guesswork with data. Here\'s how to test post variants and what to do with the results.', readTime: '5 min read', emoji: '📊', featured: false },
  { slug: 'link-in-bio-builder-2026-guide',                title: 'Link in Bio Builder: What It Is and Why You Need One in 2026',                date: 'April 2026', category: 'Features',    excerpt: 'A link in bio page is the most visited link on most creator profiles. Here\'s what it should include and how to build one for free.', readTime: '4 min read', emoji: '🔗', featured: false },
  { slug: 'competitor-tracking-social-media-strategy',     title: 'How to Track Competitors on Social Media (Without Spending Hours Doing It)',   date: 'April 2026', category: 'Tips',        excerpt: 'Knowing what competitors post, when they post, and what gets engagement is valuable intel. Here\'s how to track it without the manual work.', readTime: '5 min read', emoji: '🔭', featured: false },
  { slug: 'evergreen-content-recycling-social-media',      title: 'Evergreen Content Recycling: Get More From Posts You\'ve Already Written',     date: 'April 2026', category: 'Tips',        excerpt: 'Most posts are seen by less than 5% of your audience. Recycling evergreen content is one of the highest-leverage things you can do.', readTime: '5 min read', emoji: '🌿', featured: false },
  { slug: 'managing-multiple-social-media-clients-guide',  title: 'How to Manage Multiple Social Media Clients Without Losing Your Mind',         date: 'April 2026', category: 'Agencies',    excerpt: 'Managing five clients on five platforms is a systems problem. Here\'s the workflow that scales without adding headcount.', readTime: '6 min read', emoji: '📋', featured: false },
  { slug: 'built-socialmate-bootstrapped-deli-worker',     title: 'How I Built a SaaS on a Deli Worker\'s Budget: The Bootstrapper\'s Story',    date: 'April 2026', category: 'Our Story',   excerpt: 'No funding. No team. No fancy office. Built between shifts, on weekends, and in stolen hours. Here\'s how SocialMate went from idea to launch.', readTime: '6 min read', emoji: '❤️', featured: false },
  { slug: 'creator-os-what-it-means-home-base',            title: 'Creator OS: What It Means to Have a Home Base for Everything You Create',     date: 'April 2026', category: 'Our Story',   excerpt: 'SocialMate isn\'t just a scheduler. It\'s a Creator OS — one place for your content, analytics, AI tools, community, and monetization.', readTime: '5 min read', emoji: '🏠', featured: false },
  { slug: 'studio-stax-independent-creator-directory',     title: 'Studio Stax: The Creator Directory Built for Independent Artists',             date: 'April 2026', category: 'Features',    excerpt: 'Studio Stax connects fans and brands directly with independent musicians, podcasters, and creators — no middlemen, founder-approved listings only.', readTime: '4 min read', emoji: '🎵', featured: false },
  { slug: 'per-platform-posting-schedule-strategy',        title: 'Why You Should Have a Different Posting Schedule for Each Platform',           date: 'April 2026', category: 'Tips',        excerpt: 'Bluesky, X, Discord, and Telegram all have different peak times and audience behaviors. One schedule for all of them leaves performance on the table.', readTime: '5 min read', emoji: '📅', featured: false },
]

export default async function Blog() {
  const dbPosts  = await getDbPosts()
  const slugSet  = new Set(STATIC_POSTS.map(p => p.slug))
  // Merge: static first, then any DB posts not already in static list
  const allPosts = [
    ...STATIC_POSTS,
    ...dbPosts.filter(p => !slugSet.has(p.slug)),
  ]

  return (
    <PublicLayout>
      <div className="max-w-4xl mx-auto px-6 py-16">

        <div className="mb-8">
          <h1 className="text-3xl font-extrabold tracking-tight mb-2">Blog</h1>
          <p className="text-sm text-gray-400">Tips, guides, and updates from SocialMate</p>
        </div>

        {/* Search, category filters, featured post, and grid — all client-side */}
        <BlogClientList allPosts={allPosts} />

        <div className="mt-8 bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 rounded-2xl p-6 text-center">
          <p className="text-sm font-extrabold mb-1 text-gray-900 dark:text-gray-100">Want to try SocialMate?</p>
          <p className="text-xs text-gray-400 dark:text-gray-500 mb-4">Free forever. No credit card. No catch.</p>
          <Link href="/signup"
            className="inline-block bg-black text-white text-xs font-bold px-5 py-2.5 rounded-xl hover:opacity-80 transition-all">
            Start scheduling for free →
          </Link>
        </div>

        {/* SM-Give strip */}
        <div className="border-t border-gray-100 dark:border-gray-800 mt-16 pt-10 pb-4">
          <div className="max-w-4xl mx-auto px-6 text-center">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              ❤️ <span className="font-semibold text-gray-700 dark:text-gray-300">2% of every SocialMate subscription</span> goes to SM-Give — our charity initiative.{' '}
              <a href="/give" className="text-amber-500 hover:text-amber-400 font-semibold transition-colors">Learn about SM-Give →</a>
            </p>
          </div>
        </div>
      </div>
    </PublicLayout>
  )
}