import { MetadataRoute } from 'next'

const BLOG_SLUGS = [
  // Original 14
  'why-we-built-socialmate',
  'socialmate-gives-back-sm-give',
  'discord-scheduling-grow-your-server',
  'mastodon-scheduling-free-tool',
  'how-to-repurpose-content-across-platforms',
  'how-to-schedule-posts-on-bluesky',
  'social-media-scheduling-for-small-business',
  'free-social-media-tools-for-creators',
  'how-to-grow-bluesky-following',
  'social-media-scheduling-vs-posting-manually',
  'best-free-social-media-scheduler-2025',
  'how-to-use-ai-for-social-media-captions',
  'why-your-hashtag-strategy-isnt-working',
  'real-cost-of-social-media-management-tools-2025',
  // 12 new posts (Apr 2026)
  'how-to-schedule-telegram-posts-free',
  'bluesky-vs-twitter-where-to-post-2026',
  'social-media-content-calendar-template-2026',
  'best-time-to-post-on-bluesky',
  'discord-community-management-guide',
  'social-media-automation-solo-creators',
  'free-hootsuite-alternative-2026',
  'how-to-grow-discord-server-2026',
  'ai-social-media-tools-free-2026',
  'how-to-post-consistently-social-media',
  'mastodon-vs-bluesky-2026',
  'social-media-scheduling-agencies-freelancers',
  // 14 more posts (Apr 2026 batch 2)
  'best-social-media-scheduler-creators-2026',
  'how-to-schedule-posts-instagram-free',
  'social-media-content-ideas-2026',
  'how-to-use-bluesky-for-business',
  'pinterest-scheduling-free-tools',
  'social-media-burnout-creators',
  'how-to-grow-mastodon-following',
  'small-business-social-media-guide-2026',
  'free-link-in-bio-tools',
  'twitter-x-alternatives-2026',
  'content-calendar-for-small-business',
  'social-media-analytics-free-tools',
  'discord-for-creators-2026',
  'how-to-repurpose-one-post-ten-platforms',
  // 20 new posts (Apr 2026 batch 3)
  'x-twitter-scheduling-free',
  'bluesky-for-creators-2026',
  'social-media-tools-comparison-2026',
  'discord-bot-vs-scheduler',
  'mastodon-guide-2026',
  'free-social-media-scheduler-no-credit-card',
  'social-media-workflow-creators',
  'bluesky-algorithm-2026',
  'telegram-channel-growth',
  'social-media-scheduling-cost-breakdown',
  'hashtag-strategy-bluesky-mastodon',
  'content-repurposing-system',
  'social-media-for-nonprofits',
  'best-time-post-discord',
  'ai-content-creation-social-media',
  'social-media-strategy-small-team',
  'scheduling-vs-posting-manually-2026',
  'grow-audience-multiple-platforms',
  'social-media-analytics-what-matters',
  'decentralized-social-media-2026',
  // SocialMate batch (Apr 2026)
  'schedule-posts-bluesky-free',
  'best-discord-scheduler-2026',
  'telegram-marketing-guide-2026',
  'build-social-media-content-calendar-free',
  'ai-caption-generator-social-media-2026',
  'mastodon-marketing-guide-2026',
  'link-in-bio-tools-compared-2026',
  'bulk-schedule-social-media-posts',
  'evergreen-content-strategy-social-media',
  'team-social-media-workflow-small-teams',
  'rss-to-social-media-automation',
  'competitor-tracking-social-media-free',
  'why-free-social-media-tools-are-winning',
  'social-media-analytics-what-to-track',
  'x-twitter-posting-strategy-2026',
  // RenewalMate batch (Apr 2026)
  'renewalmate-review-2026',
  'how-to-track-subscriptions-free',
  'best-subscription-tracker-apps-2026',
  'cancel-forgotten-subscriptions-save-money',
  'subscription-fatigue-how-to-fight-it',
  'renewalmate-vs-rocket-money',
  'annual-subscription-renewal-tips',
  'free-tools-for-freelancers-2026',
  'renewalmate-for-small-business-owners',
  // Enki batch (Apr 2026)
  'what-is-enki-trading-bot',
  'paper-trading-before-going-live',
  'what-is-algorithmic-trading-beginners',
  'congressional-trading-disclosures-explained',
  'enki-vs-3commas-vs-cryptohopper',
  'fortress-guard-trading-risk-management',
  'how-to-start-investing-algorithmically',
  'reddit-sentiment-stock-trading-signals',
  'enki-leaderboard-explained',
  'stocks-vs-crypto-algorithmic-trading',
  'pdt-rule-explained-how-to-avoid',
  'enki-cloud-runner-explained',
  'enki-vs-wealthfront-vs-betterment',
  // Batch 7 (Apr 2026)
  'how-to-use-discord-webhooks-for-social-media',
  'social-media-scheduling-for-streamers',
  'bluesky-custom-feeds-guide',
  'telegram-channel-vs-group-creators',
  'mastodon-instances-guide-2026',
  'how-to-batch-social-media-content',
  'social-media-analytics-small-business',
  'link-in-bio-strategy-creators',
  'how-to-grow-social-media-from-zero',
  'social-media-content-pillars',
  'white-label-social-media-tool',
  'agency-social-media-workflow',
  'twitch-clip-marketing-strategy',
  'youtube-clip-repurposing',
  'ai-content-creation-workflow',
  'how-to-use-rss-for-social-media',
  'competitor-analysis-social-media',
  'social-media-team-workflow',
  'evergreen-content-strategy',
  'hashtag-research-guide-2026',
  // Batch 8 (Apr 2026)
  'how-to-grow-on-bluesky-without-followers',
  'social-media-for-real-estate-agents-2026',
  'content-batching-complete-guide',
  'how-to-write-a-social-media-bio-that-converts',
  'telegram-vs-discord-which-is-better-for-creators',
  'mastodon-beginners-guide-2026',
  'how-to-use-ai-for-social-media-content',
  'how-to-repurpose-content-across-platforms',
  'social-media-roi-how-to-measure-what-matters',
  'small-business-social-media-strategy-2026',
  'how-to-build-a-personal-brand-on-social-media',
  'social-media-scheduling-tools-compared-2026',
  'discord-for-creators-complete-guide',
  'what-is-social-media-automation',
  'how-to-post-consistently-on-social-media',
  'best-time-to-post-on-social-media-2026',
  'how-to-grow-your-telegram-channel',
  'social-media-for-nonprofits-guide',
  'how-to-schedule-posts-in-advance',
  'creator-economy-trends-2026',
  'social-media-content-calendar-how-to-build-one',
  // Business & Finance batch (May 2026)
  'how-to-get-duns-number-free-2026',
  'paydex-score-build-business-credit-scratch',
  'tax-deductions-self-employed-creators-2026',
  'wyoming-llc-solo-founders-why',
  'how-to-schedule-tiktok-posts-2026',
  'section-179-deduction-2026-write-off-tech',
  'home-office-tax-deduction-2026-guide',
  'building-software-working-deli-job-founder',
  'gilgamesh-guides-free-business-playbooks',
  'get-first-business-client-no-network',
  's-corp-election-when-it-makes-sense-2026',
  'qbi-deduction-20-percent-self-employed-2026',
  'content-flywheel-create-once-post-everywhere',
  'solo-founder-systems-build-without-team-2026',
  'validate-business-idea-reddit-48-hours-method',
  'net-30-vendors-report-dun-bradstreet-list',
  'tiktok-scheduling-free-tool-creators-2026',
  'bluesky-organic-reach-why-it-works-2026',
  'startup-costs-deduction-section-195-explained',
  'sep-ira-self-employed-retirement-tax-strategy',
  // Vibe Coding & AI Builder batch (May 2026)
  'vibe-coding-what-it-is-how-to-start',
  'build-saas-no-cs-degree-ai-2026',
  'claude-code-review-solo-founder',
  'best-ai-coding-tools-solo-founders-2026',
  'nextjs-supabase-starter-stack-2026',
  'how-to-prompt-ai-for-coding-beginners',
  'ship-software-faster-with-ai-workflow',
  'building-saas-working-full-time-job',
  'free-stack-build-saas-zero-cost-2026',
  'solo-founder-tech-stack-no-team-2026',
]

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://socialmate.studio'
  const now  = new Date()

  const core: MetadataRoute.Sitemap = [
    { url: base,                          lastModified: now, changeFrequency: 'weekly',  priority: 1   },
    { url: `${base}/pricing`,             lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/features`,            lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/studio-stax`,         lastModified: now, changeFrequency: 'weekly',  priority: 0.8 },
    { url: `${base}/studio-stax/apply`,   lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/give`,                lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/partners`,            lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/signup`,              lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/login`,               lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/story`,               lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/roadmap`,             lastModified: now, changeFrequency: 'weekly',  priority: 0.7 },
    { url: `${base}/affiliates`,           lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/merch`,               lastModified: now, changeFrequency: 'weekly',  priority: 0.7 },
    { url: `${base}/faq`,                 lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/beta`,               lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/analytics`,           lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/calendar`,            lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: `${base}/blog`,                lastModified: now, changeFrequency: 'weekly',  priority: 0.8 },
    { url: `${base}/vs`,                  lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/privacy`,             lastModified: now, changeFrequency: 'yearly',  priority: 0.3 },
    { url: `${base}/terms`,               lastModified: now, changeFrequency: 'yearly',  priority: 0.3 },
    { url: `${base}/enki`,               lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/enki/leaderboard`,   lastModified: now, changeFrequency: 'daily',   priority: 0.7 },
    { url: `${base}/enki/dashboard`,     lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/enki/trades`,        lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/enki/settings`,      lastModified: now, changeFrequency: 'monthly', priority: 0.4 },
    { url: `${base}/gilgamesh`,          lastModified: now, changeFrequency: 'weekly',  priority: 0.8 },
    { url: `${base}/guides`,                          lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/guides/starting-a-business`,    lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/marketing-zero-budget`,   lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/business-credit-legal`,   lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/vibe-coding-with-ai`,     lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support`,            lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/changelog`,          lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/clips`,              lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/create`,             lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/for/streamers`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/for/agencies`,       lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/for/small-business`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/referral`,           lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/refer`,              lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/analytics/dna`,      lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/monetize`,           lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
  ]

  const comparisons: MetadataRoute.Sitemap = [
    { url: `${base}/vs/hootsuite`,    lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/buffer`,       lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/later`,        lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/sendible`,     lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/metricool`,    lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/publer`,       lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/planable`,     lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/sprout-social`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/socialpilot`,  lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/zoho-social`,  lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/socialrails`,  lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/vs/loomly`,         lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/coschedule`,     lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/meetedgar`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/iconosquare`,    lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/tailwind-social`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/crowdfire`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/pallyy`,         lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/agorapulse`,     lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/sprinklr`,       lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/socialbee`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/contentstudio`,  lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/missinglettr`,   lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/postplanner`,    lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/recurpost`,      lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/nuelink`,        lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/fedica`,         lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/statusbrew`,     lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/tweetdeck`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/eclincher`,      lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/oktopost`,       lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/napoleon-cat`,   lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/hopper-hq`,      lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/sked-social`,    lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/onlypult`,       lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/smarterqueue`,   lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/hypefury`,       lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/typefully`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/postcron`,       lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
  ]

  const blogPosts: MetadataRoute.Sitemap = BLOG_SLUGS.map(slug => ({
    url: `${base}/blog/${slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.6,
  }))

  return [...core, ...comparisons, ...blogPosts]
}
