import { MetadataRoute } from 'next'

const BLOG_SLUGS = [
  // Original 14
  'why-we-built-socialmate',
  'socialmate-gives-back-sm-give',
  'discord-scheduling-grow-your-server',
  'mastodon-scheduling-free-tool',
  'how-to-repurpose-content-across-platforms',
  'how-to-schedule-posts-on-bluesky',
  'social-media-scheduling-for-small-business',
  'free-social-media-tools-for-creators',
  'how-to-grow-bluesky-following',
  'social-media-scheduling-vs-posting-manually',
  'best-free-social-media-scheduler-2025',
  'how-to-use-ai-for-social-media-captions',
  'why-your-hashtag-strategy-isnt-working',
  'real-cost-of-social-media-management-tools-2025',
  // 12 new posts (Apr 2026)
  'how-to-schedule-telegram-posts-free',
  'bluesky-vs-twitter-where-to-post-2026',
  'social-media-content-calendar-template-2026',
  'best-time-to-post-on-bluesky',
  'discord-community-management-guide',
  'social-media-automation-solo-creators',
  'free-hootsuite-alternative-2026',
  'how-to-grow-discord-server-2026',
  'ai-social-media-tools-free-2026',
  'how-to-post-consistently-social-media',
  'mastodon-vs-bluesky-2026',
  'social-media-scheduling-agencies-freelancers',
  // 14 more posts (Apr 2026 batch 2)
  'best-social-media-scheduler-creators-2026',
  'how-to-schedule-posts-instagram-free',
  'social-media-content-ideas-2026',
  'how-to-use-bluesky-for-business',
  'pinterest-scheduling-free-tools',
  'social-media-burnout-creators',
  'how-to-grow-mastodon-following',
  'small-business-social-media-guide-2026',
  'free-link-in-bio-tools',
  'twitter-x-alternatives-2026',
  'content-calendar-for-small-business',
  'social-media-analytics-free-tools',
  'discord-for-creators-2026',
  'how-to-repurpose-one-post-ten-platforms',
  // 20 new posts (Apr 2026 batch 3)
  'x-twitter-scheduling-free',
  'bluesky-for-creators-2026',
  'social-media-tools-comparison-2026',
  'discord-bot-vs-scheduler',
  'mastodon-guide-2026',
  'free-social-media-scheduler-no-credit-card',
  'social-media-workflow-creators',
  'bluesky-algorithm-2026',
  'telegram-channel-growth',
  'social-media-scheduling-cost-breakdown',
  'hashtag-strategy-bluesky-mastodon',
  'content-repurposing-system',
  'social-media-for-nonprofits',
  'best-time-post-discord',
  'ai-content-creation-social-media',
  'social-media-strategy-small-team',
  'scheduling-vs-posting-manually-2026',
  'grow-audience-multiple-platforms',
  'social-media-analytics-what-matters',
  'decentralized-social-media-2026',
  // SocialMate batch (Apr 2026)
  'schedule-posts-bluesky-free',
  'best-discord-scheduler-2026',
  'telegram-marketing-guide-2026',
  'build-social-media-content-calendar-free',
  'ai-caption-generator-social-media-2026',
  'mastodon-marketing-guide-2026',
  'link-in-bio-tools-compared-2026',
  'bulk-schedule-social-media-posts',
  'evergreen-content-strategy-social-media',
  'team-social-media-workflow-small-teams',
  'rss-to-social-media-automation',
  'competitor-tracking-social-media-free',
  'why-free-social-media-tools-are-winning',
  'social-media-analytics-what-to-track',
  'x-twitter-posting-strategy-2026',
  // RenewalMate batch (Apr 2026)
  'renewalmate-review-2026',
  'how-to-track-subscriptions-free',
  'best-subscription-tracker-apps-2026',
  'cancel-forgotten-subscriptions-save-money',
  'subscription-fatigue-how-to-fight-it',
  'renewalmate-vs-rocket-money',
  'annual-subscription-renewal-tips',
  'free-tools-for-freelancers-2026',
  'renewalmate-for-small-business-owners',
  // Enki batch (Apr 2026)
  'what-is-enki-trading-bot',
  'paper-trading-before-going-live',
  'what-is-algorithmic-trading-beginners',
  'congressional-trading-disclosures-explained',
  'enki-vs-3commas-vs-cryptohopper',
  'fortress-guard-trading-risk-management',
  'how-to-start-investing-algorithmically',
  'reddit-sentiment-stock-trading-signals',
  'enki-leaderboard-explained',
  'stocks-vs-crypto-algorithmic-trading',
  'pdt-rule-explained-how-to-avoid',
  'enki-cloud-runner-explained',
  'enki-vs-wealthfront-vs-betterment',
  // Batch 7 (Apr 2026)
  'how-to-use-discord-webhooks-for-social-media',
  'social-media-scheduling-for-streamers',
  'bluesky-custom-feeds-guide',
  'telegram-channel-vs-group-creators',
  'mastodon-instances-guide-2026',
  'how-to-batch-social-media-content',
  'social-media-analytics-small-business',
  'link-in-bio-strategy-creators',
  'how-to-grow-social-media-from-zero',
  'social-media-content-pillars',
  'white-label-social-media-tool',
  'agency-social-media-workflow',
  'twitch-clip-marketing-strategy',
  'youtube-clip-repurposing',
  'ai-content-creation-workflow',
  'how-to-use-rss-for-social-media',
  'competitor-analysis-social-media',
  'social-media-team-workflow',
  'evergreen-content-strategy',
  'hashtag-research-guide-2026',
  // Batch 8 (Apr 2026)
  'how-to-grow-on-bluesky-without-followers',
  'social-media-for-real-estate-agents-2026',
  'content-batching-complete-guide',
  'how-to-write-a-social-media-bio-that-converts',
  'telegram-vs-discord-which-is-better-for-creators',
  'mastodon-beginners-guide-2026',
  'how-to-use-ai-for-social-media-content',
  'how-to-repurpose-content-across-platforms',
  'social-media-roi-how-to-measure-what-matters',
  'small-business-social-media-strategy-2026',
  'how-to-build-a-personal-brand-on-social-media',
  'social-media-scheduling-tools-compared-2026',
  'discord-for-creators-complete-guide',
  'what-is-social-media-automation',
  'how-to-post-consistently-on-social-media',
  'best-time-to-post-on-social-media-2026',
  'how-to-grow-your-telegram-channel',
  'social-media-for-nonprofits-guide',
  'how-to-schedule-posts-in-advance',
  'creator-economy-trends-2026',
  'social-media-content-calendar-how-to-build-one',
  // Business & Finance batch (May 2026)
  'how-to-get-duns-number-free-2026',
  'paydex-score-build-business-credit-scratch',
  'tax-deductions-self-employed-creators-2026',
  'wyoming-llc-solo-founders-why',
  'how-to-schedule-tiktok-posts-2026',
  'section-179-deduction-2026-write-off-tech',
  'home-office-tax-deduction-2026-guide',
  'building-software-working-deli-job-founder',
  'gilgamesh-guides-free-business-playbooks',
  'get-first-business-client-no-network',
  's-corp-election-when-it-makes-sense-2026',
  'qbi-deduction-20-percent-self-employed-2026',
  'content-flywheel-create-once-post-everywhere',
  'solo-founder-systems-build-without-team-2026',
  'validate-business-idea-reddit-48-hours-method',
  'net-30-vendors-report-dun-bradstreet-list',
  'tiktok-scheduling-free-tool-creators-2026',
  'bluesky-organic-reach-why-it-works-2026',
  'startup-costs-deduction-section-195-explained',
  'sep-ira-self-employed-retirement-tax-strategy',
  // Vibe Coding & AI Builder batch (May 2026)
  'vibe-coding-what-it-is-how-to-start',
  'build-saas-no-cs-degree-ai-2026',
  'claude-code-review-solo-founder',
  'best-ai-coding-tools-solo-founders-2026',
  'nextjs-supabase-starter-stack-2026',
  'how-to-prompt-ai-for-coding-beginners',
  'ship-software-faster-with-ai-workflow',
  'building-saas-working-full-time-job',
  'free-stack-build-saas-zero-cost-2026',
  'solo-founder-tech-stack-no-team-2026',
  // Platform Schedulers + Competitor Alternatives batch (May 2026)
  'best-social-media-scheduler-2026',
  'best-twitter-x-scheduler-2026',
  'best-bluesky-scheduler-tool',
  'best-mastodon-scheduler-2026',
  'best-discord-scheduler-tool',
  'best-telegram-scheduler-2026',
  'social-media-scheduling-tools-comparison',
  'free-social-media-scheduler-2026',
  'cheapest-social-media-scheduler',
  'multi-platform-social-media-scheduler',
  'buffer-alternative-cheaper',
  'hootsuite-alternative-2026',
  'sprout-social-alternative-affordable',
  'later-alternative-social-media',
  'publer-alternative-2026',
  'metricool-alternative-2026',
  'planoly-alternative-2026',
  'zoho-social-alternative',
  'sendible-alternative-2026',
  'agorapulse-alternative',
  'crowdfire-alternative',
  'socialbee-alternative',
  'loomly-alternative',
  'contentstudio-alternative',
  'missinglettr-alternative',
  // How-To Guides + AI Tools batch (May 2026)
  'how-to-schedule-posts-bluesky',
  'how-to-schedule-posts-mastodon',
  'how-to-post-discord-automatically',
  'how-to-schedule-telegram-posts',
  'how-to-automate-social-media-posts',
  'how-to-build-social-media-content-calendar',
  'how-to-repurpose-content-multiple-platforms',
  'how-to-use-ai-write-social-media-posts',
  'how-to-schedule-x-twitter-posts',
  'ai-social-media-caption-generator',
  'ai-hashtag-generator-social-media',
  'ai-content-repurposing-tool',
  'best-ai-tools-content-creators-2026',
  'ai-social-media-content-calendar',
  'ai-post-scheduler-2026',
  'ai-writing-assistant-social-media',
  'how-to-use-ai-social-media-marketing',
  'ai-social-media-manager',
  'gemini-ai-social-media-posts',
  // Creator Guides + Founder Story batch (May 2026)
  'social-media-strategy-small-business-2026',
  'content-calendar-template-creators',
  'how-to-grow-social-media-without-budget',
  'social-media-tips-solo-founders',
  'best-social-media-platforms-small-business',
  'social-media-engagement-tips-2026',
  'build-audience-multiple-platforms',
  'social-media-roi-small-business',
  'creator-economy-tools-2026',
  'building-saas-solo-no-funding',
  'how-to-bootstrap-startup-2026',
  'solo-founder-tools-2026',
  'bootstrapped-saas-success-story',
  'shipping-software-side-hustle',
  'social-media-for-streamers-2026',
  'twitter-bluesky-mastodon-comparison',
  // Batch 9 — SM-Give, Creator Monetization, BDAY31, SOMA, Enki, Studio Stax, Founder, i18n, Creator Economy (May 2026)
  'what-is-sm-give',
  'sm-give-2-percent-subscription',
  'building-a-giving-business-from-scratch',
  'social-media-tool-that-donates',
  'sm-give-helping-homeless-single-parents-schools',
  'creator-tool-with-charity-built-in',
  'how-to-make-money-as-creator-2026',
  'tip-jar-complete-guide-creators',
  'fan-subscriptions-recurring-income-creators',
  'sell-digital-products-as-creator',
  'first-brand-deal-micro-influencer-guide',
  'affiliate-marketing-guide-creators',
  'free-creator-monetization-guide',
  'gilgamesh-guide-vol-5-explained',
  '12-month-5k-month-creator-roadmap',
  'bday31-promo-explained',
  'best-social-media-tool-deal-2026',
  'socialmate-under-4-dollars-month',
  'deli-job-founder-shipping-software-2am',
  '50-features-solo-bootstrapped-60-days',
  'bootstrapped-saas-playbook-2026',
  'cofounder-search-sweat-equity-startup',
  'socialmate-7-languages-global',
  'multi-language-social-media-scheduler',
  'how-we-built-nextjs-i18n-no-plugins',
  'soma-voice-dna-your-brand-voice',
  'soma-project-memory-never-repeat',
  'soma-vs-ai-content-tools',
  'one-click-week-of-content-soma',
  'enki-truth-mode-explained',
  'why-paper-trading-matters',
  'enki-citizen-free-trading-bot',
  'studio-stax-creator-tools-directory',
  'how-to-get-listed-studio-stax',
  'studio-stax-founding-member-worth-it',
  'creator-economy-what-works-2026',
  'nonprofits-social-media-scheduling',
  'small-creators-vs-big-brands-algorithm',
  'why-5-dollars-month-affordable-creator-tool',
  'gilgamesh-guides-overview',
  // Batch 10 — TikTok scheduling, Twitch/YouTube clips, video content, GIFs, creator tools (May 2026)
  'schedule-tiktok-posts-free',
  'best-tiktok-scheduler-2026',
  'tiktok-content-calendar-guide',
  'auto-schedule-tiktok-posts',
  'tiktok-scheduling-api-explained',
  'socialmate-tiktok-scheduler',
  'schedule-twitch-clips-to-social-media',
  'repurpose-twitch-clips-guide',
  'youtube-shorts-scheduler-free-2026',
  'twitch-to-tiktok-workflow',
  'clips-studio-guide',
  'short-form-video-strategy-2026',
  'repurpose-long-form-video-to-social',
  'video-content-calendar-creator',
  'vertical-video-guide-social-media',
  'tiktok-youtube-shorts-cross-posting',
  'animated-gifs-social-media-2026',
  'create-gifs-for-social-media',
  'gifs-vs-video-social-media',
  'tiktok-gif-content-strategy',
  'best-tools-tiktok-creators-2026',
  'youtube-creator-social-tools-stack',
  'twitch-streamer-growth-tools',
  'video-creator-content-workflow',
  'streamer-social-media-strategy',
  'tiktok-algorithm-explained-2026',
  'tiktok-hashtag-strategy-guide',
  'grow-tiktok-from-zero',
  'tiktok-analytics-guide-creators',
  'tiktok-content-ideas-2026',
  // Batch 11 — social media strategy, content creation, platform guides (May 2026)
  'social-media-content-calendar-template-2026-guide',
  'how-often-should-you-post-on-social-media-2026',
  'best-time-to-post-on-social-media-by-platform-2026',
  'social-media-engagement-rate-by-platform-2026',
  'how-to-grow-social-media-following-from-scratch',
  'social-media-strategy-for-small-business-2026-complete',
  'how-to-write-social-media-captions-that-get-engagement',
  'viral-social-media-post-ideas-2026',
  'how-to-repurpose-blog-content-for-social-media',
  'social-media-content-ideas-evergreen',
  'how-to-use-ai-to-write-social-media-posts-2026',
  'content-pillars-for-social-media-strategy',
  'how-to-grow-on-bluesky-2026',
  'discord-server-marketing-tips-for-creators',
  'telegram-channel-growth-strategy-2026',
  'mastodon-for-business-guide-2026',
  'how-to-get-more-tiktok-followers-2026',
  'x-twitter-growth-strategy-2026',
  'social-media-management-for-agencies-guide',
  'client-social-media-reporting-templates-2026',
  'how-to-manage-multiple-social-media-accounts',
  'social-media-white-label-tools-for-agencies',
  'how-creators-make-money-online-2026',
  'creator-economy-statistics-2026',
  'how-to-build-a-personal-brand-online-2026',
  'social-media-tools-for-content-creators-2026',
  'link-in-bio-tools-comparison-2026',
  'ai-social-media-tools-2026-guide',
  'how-to-automate-social-media-posting-guide',
  'ai-content-generation-for-social-media-2026',
  'social-media-scheduling-automation-complete-guide',
  'social-media-marketing-for-small-business-2026',
  'how-to-use-social-media-for-local-business',
  'social-media-for-restaurants-2026',
  'nonprofit-social-media-strategy-2026',
  // Batch 12 (May 2026)
  'zenith-creator-card-share-your-presence',
  'hestia-community-for-creators-socialmate',
  'sigil-link-in-bio-creator-landing-page',
  '30-day-creator-challenge-how-it-works',
  'socialmate-achievements-badges-creator-milestones',
  'how-to-grow-social-media-without-paid-ads',
  'content-batching-system-for-creators',
  'finding-your-content-niche-guide-2026',
  'how-to-build-an-audience-from-zero-in-2026',
  'creator-consistency-why-it-beats-talent',
  'repurposing-one-idea-into-ten-posts',
  'social-media-posting-schedule-for-beginners',
  'content-strategy-for-solo-creators-2026',
  'discord-growth-strategy-for-creators-2026',
  'telegram-channel-marketing-guide-2026',
  'bluesky-growth-tips-for-creators-2026',
  'mastodon-for-creators-complete-guide',
  'x-twitter-growth-tips-2026-algorithm',
  'tiktok-for-small-business-complete-guide-2026',
  'how-to-write-hooks-that-stop-the-scroll',
  'content-pillars-strategy-build-your-brand',
  'storytelling-for-social-media-creators',
  'evergreen-content-strategy-2026',
  'captions-that-drive-engagement-formula',
  'batch-content-creation-weekend-workflow',
  'how-to-use-ai-for-content-creation-2026',
  'multiple-income-streams-for-creators',
  'brand-deals-for-micro-influencers-2026',
  'creator-pricing-how-much-to-charge',
  'musicians-social-media-strategy-2026',
  'podcasters-social-media-strategy-2026',
  'affiliate-marketing-for-creators-beginners',
  'social-media-scheduling-tools-comparison-2026',
  'brand-voice-ai-guide-for-creators',
  'automate-social-media-without-losing-authenticity',
  'free-tools-for-creators-2026',
  'social-media-workflow-for-busy-people',
  'social-media-analytics-what-actually-matters',
  'best-time-to-post-platform-deep-dive-2026',
  'how-to-improve-social-media-engagement-rate',
  'reach-vs-engagement-which-matters-more',
  'social-media-audit-how-to-do-one',
  'social-media-for-coaches-and-consultants',
  'social-media-for-freelancers-get-clients',
  'fitness-influencer-social-media-strategy',
  'travel-creator-social-media-strategy-2026',
  'food-blogger-social-media-strategy-2026',
  'teachers-educators-social-media-guide-2026',
  'artist-social-media-strategy-grow-your-art-brand',
  'creator-burnout-prevention-guide',
  'sustainable-posting-schedule-avoid-exhaustion',
  'work-life-balance-for-creators-remote-workers',
  'build-loyal-community-around-your-content',
  'discord-community-vs-telegram-channel-which-is-better',
  'turning-lurkers-into-community-members',
  // LinkedIn launch batch (May 2026)
  'free-linkedin-post-scheduler-2026',
  'how-to-schedule-linkedin-posts-free',
  'best-linkedin-scheduler-2026',
  'linkedin-content-strategy-2026',
  'linkedin-algorithm-2026',
  'best-time-to-post-on-linkedin-2026',
  'linkedin-for-creators-2026',
  'schedule-linkedin-posts-free-tool',
  'linkedin-hook-writing-guide-2026',
  'linkedin-personal-brand-2026',
  'linkedin-vs-twitter-creators-2026',
  'linkedin-vs-bluesky-2026',
  'linkedin-scheduling-best-practices-2026',
  'linkedin-content-ideas-2026',
  'how-to-grow-linkedin-following-2026',
  'cross-post-linkedin-bluesky-twitter-2026',
  'linkedin-repurpose-content-strategy',
  'linkedin-ai-content-tools-2026',
  'socialmate-linkedin-integration-launch',
  // Batch 13 — LinkedIn scheduling, TikTok scheduling, multi-platform (May 2026)
  'how-to-schedule-linkedin-posts-free',
  'best-linkedin-post-scheduler-2026',
  'linkedin-scheduling-tool-comparison',
  'schedule-linkedin-posts-in-advance',
  'free-linkedin-scheduler-no-credit-card',
  'linkedin-content-strategy-2026',
  'linkedin-algorithm-explained-2026',
  'linkedin-post-ideas-creators',
  'best-time-to-post-on-linkedin',
  'linkedin-vs-twitter-for-creators',
  'how-to-schedule-tiktok-posts-free',
  'best-tiktok-scheduler-2026',
  'tiktok-scheduling-tool-comparison',
  'schedule-tiktok-in-advance',
  'free-tiktok-content-planner',
  'tiktok-content-strategy-for-beginners',
  'tiktok-algorithm-2026',
  'best-time-to-post-on-tiktok-2026',
  'tiktok-for-business-2026',
  'tiktok-scheduling-api',
  'schedule-tiktok-and-linkedin-same-tool',
  'social-media-scheduler-7-platforms',
  'discord-telegram-social-media-scheduling',
  'multi-platform-social-media-strategy',
  'social-media-scheduling-tools-small-business',
  'bluesky-linkedin-tiktok-scheduler',
  'creator-os-2026',
  'ai-social-media-tools-2026',
  'social-media-automation-small-business',
  'hootsuite-alternative-with-tiktok-linkedin',
]

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://socialmate.studio'
  const now  = new Date()

  const core: MetadataRoute.Sitemap = [
    { url: base,                          lastModified: now, changeFrequency: 'weekly',  priority: 1   },
    { url: `${base}/pricing`,             lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/features`,            lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/studio-stax`,         lastModified: now, changeFrequency: 'weekly',  priority: 0.8 },
    { url: `${base}/studio-stax/apply`,   lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/give`,                lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/wall-of-love`,        lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/discount`,            lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/partners`,            lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/signup`,              lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/login`,               lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/story`,               lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/roadmap`,             lastModified: now, changeFrequency: 'weekly',  priority: 0.7 },
    { url: `${base}/affiliates`,           lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/merch`,               lastModified: now, changeFrequency: 'weekly',  priority: 0.7 },
    { url: `${base}/faq`,                 lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/integrations`,        lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/hashtag-collections`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/beta`,               lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/analytics`,           lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/calendar`,            lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: `${base}/blog`,                lastModified: now, changeFrequency: 'weekly',  priority: 0.8 },
    { url: `${base}/vs`,                  lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/privacy`,             lastModified: now, changeFrequency: 'yearly',  priority: 0.3 },
    { url: `${base}/terms`,               lastModified: now, changeFrequency: 'yearly',  priority: 0.3 },
    { url: `${base}/enki`,               lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/enki/leaderboard`,   lastModified: now, changeFrequency: 'daily',   priority: 0.7 },
    { url: `${base}/enki/dashboard`,     lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/enki/trades`,        lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/enki/settings`,      lastModified: now, changeFrequency: 'monthly', priority: 0.4 },
    { url: `${base}/gilgamesh`,          lastModified: now, changeFrequency: 'weekly',  priority: 0.8 },
    { url: `${base}/guides`,                          lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/guides/starting-a-business`,    lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/marketing-zero-budget`,   lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/business-credit-legal`,   lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/vibe-coding-with-ai`,     lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/creator-monetization`,   lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support`,            lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/changelog`,          lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/clips`,              lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/create`,             lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/for/streamers`,        lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/for/agencies`,         lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/for/small-business`,   lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/for/tiktok-creators`,   lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/for/video-creators`,    lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/for/linkedin-creators`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/referral`,           lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/refer`,              lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/analytics/dna`,      lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/monetize`,           lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/glossary`,           lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/community`,          lastModified: now, changeFrequency: 'daily',   priority: 0.7 },
    { url: `${base}/achievements`,       lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/challenge`,          lastModified: now, changeFrequency: 'weekly',  priority: 0.7 },
    { url: `${base}/zenith`,             lastModified: now, changeFrequency: 'weekly',  priority: 0.7 },
    { url: `${base}/sm-pulse`,           lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
    { url: `${base}/sm-radar`,           lastModified: now, changeFrequency: 'weekly',  priority: 0.6 },
  ]

  const comparisons: MetadataRoute.Sitemap = [
    { url: `${base}/vs/hootsuite`,    lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/buffer`,       lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/later`,        lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/sendible`,     lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/metricool`,    lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/publer`,       lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/planable`,     lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/sprout-social`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/socialpilot`,  lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/zoho-social`,  lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/socialrails`,  lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/vs/loomly`,         lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/coschedule`,     lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/meetedgar`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/iconosquare`,    lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/tailwind-social`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/crowdfire`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/pallyy`,         lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/agorapulse`,     lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/sprinklr`,       lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/socialbee`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/contentstudio`,  lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/missinglettr`,   lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/postplanner`,    lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/recurpost`,      lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/nuelink`,        lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/fedica`,         lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/statusbrew`,     lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/tweetdeck`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/eclincher`,      lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/oktopost`,       lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/napoleon-cat`,   lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/hopper-hq`,      lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/sked-social`,    lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/onlypult`,       lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/smarterqueue`,   lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/hypefury`,       lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/typefully`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/postcron`,       lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/planly`,         lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/vista-social`,   lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/flick`,          lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/canva`,          lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/plann`,          lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/social-champ`,   lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/ripl`,           lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/preview-app`,    lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/gain-app`,       lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/kontentino`,     lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/unum`,           lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/taplio`,         lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/shield-app`,     lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/tweethunter`,    lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/circleboom`,     lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/postly`,         lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/promo-republic`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/socialoomph`,    lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/tweepsmap`,      lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/audiense`,       lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/hubspot-social`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/semrush-social`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/later-free`,     lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/vs/storychief`,     lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/oneup`,          lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/brand24`,        lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/post-beyond`,    lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/combin`,         lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/keystroke`,      lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/mention`,        lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/emplifi`,        lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/postoplan`,      lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/social-report`,  lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/khoros`,         lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/vs/talkwalker`,     lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
  ]

  const blogPosts: MetadataRoute.Sitemap = BLOG_SLUGS.map(slug => ({
    url: `${base}/blog/${slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.6,
  }))

  return [...core, ...comparisons, ...blogPosts]
}
